### ISSUE TITLE
Remove logging.basicConfig call from root package __init__

### ISSUE THREAD

**Issue by inkychris** [thiagofigueiro/nexus3-cli#112]
`logging.basicConfig` is called in the main package `__init__.py`. This means that it is called even when just importing the API. This should only be called in end user code, ie. scripts that behave as command-line interfaces, therefore, perhaps a more appropriate place for this would be in `cli.__init__.py` if that is what is defining the CLI.

**Comment by thiagofigueiro** [comment]
Hi, @inkychris - as long as developers importing the API do their own `logging` configuration, I don't see a problem with this suggestion. Thanks for creating the issue.
