### ISSUE TITLE
i get nexuscli.exception.NexusClientAPIError: <exception str() failed> trying to list the repositories

### ISSUE THREAD

**Issue by pelos** [thiagofigueiro/nexus3-cli#121]
for some reason i cannot connect to the client
```
nexus_config = nexuscli.nexus_config.NexusConfig(username=NEXUS_USER,
                                                 password=NEXUS_PASSWORD,
                                                 url=NEXUS_URL,
                                                 x509_verify=False)
nexus_client = nexuscli.nexus_client.NexusClient(config=nexus_config)
print(nexus_client.repositories.list)
```

i get:
`nexuscli.exception.NexusClientAPIError: <exception str() failed>`

but if i do a manual call to api using the request library like uploading a file such:
```
import requests
files = {
    'raw.directory': (None, 'testing/testing2'),
    'raw.asset1': ('temp_sftp_files/testing.zip;application/x-zip-compressed', open('temp_sftp_files/testing.zip', 'rb')),
    'raw.asset1.filename': (None, 'testing3.zip'),
}
response = requests.post('https://my_site.net/service/rest/v1/components?repository=my_repo', files=files, auth=(NEXUS_USER, NEXUS_PASSWORD), verify=False)
print(response)
print(response.text)
```

so i know that i have the right user and password,   i am missing something?
super thanks =)

**Comment by thiagofigueiro** [comment]
https://github.com/thiagofigueiro/nexus3-cli/issues/120#issue-606759708

**Comment by thiagofigueiro** [comment]
Hard to say just looking at it, @pelos. If you open a bug in the new issue tracker (see linked comment), I can try to reproduce. Please remember to add nexus version, nexus3cli version.

**Comment by pelos** [comment]
hi, thanks, sorry got stuck with work in another project.
    El domingo, 1 de noviembre de 2020 23:56:45 GMT-6, Thiago Figueiró <notifications@github.com> escribió:  
 
 


Hard to say just looking at it, @pelos. If you open a bug in the new issue tracker (see linked comment), I can try to reproduce. Please remember to add nexus version, nexus3cli version.
