### ISSUE TITLE
Doesn't add `cleanup_policy` while creating a repository.

### ISSUE THREAD

**Issue by sahilsk** [thiagofigueiro/nexus3-cli#31]
Feature request
- add `cleanup_policy` attribute in create-repository action

**Comment by thiagofigueiro** [comment]
This is new from 3.14 (iirc). If there's REST API support, it should be easy to implement. Otherwise we're stuck with the Groovy script hacks.

**Comment by thiagofigueiro** [comment]
The Cleanup Policy creation dependency for this is now available in version 2.0.0a2 (`pip install nexus3-cli==2.0.0a2`). Still need to implement the API and CLI code to use a policy in a repository.

**Comment by thiagofigueiro** [comment]
`nexus3 repository create` now accepts `--cleanup` from version 2.0.0a3 (`pip install nexus3-cli==2.0.0a3`)
