### ISSUE TITLE
1.0.2 SyntaxError with Python 2.7

### ISSUE THREAD

**Issue by psharkey** [thiagofigueiro/nexus3-cli#43]
Looks to be caused by: https://github.com/thiagofigueiro/nexus3-cli/commit/a43e01875c51f8fb3b4152164648ddf3981e8295#diff-67d9082bd31cecf1378914edfd204ad3

```
$ nexus3 repo list
Traceback (most recent call last):
  File "/usr/local/bin/nexus3", line 7, in <module>
    from nexuscli.cli import main
  File "/usr/local/lib/python2.7/site-packages/nexuscli/__init__.py", line 2, in <module>
    from . import cli, exception, nexus_client
  File "/usr/local/lib/python2.7/site-packages/nexuscli/cli.py", line 70, in <module>
    from .nexus_client import NexusClient
  File "/usr/local/lib/python2.7/site-packages/nexuscli/nexus_client.py", line 292
    query['keyword'] = f'"{path_filter}"'  # hacky as fuck :(
                                        ^
SyntaxError: invalid syntax
$ python --version
Python 2.7.14
$
```

**Comment by nikolaev14** [comment]
Hi, if you watch in commits, you can see that python2 unsupport.
https://github.com/thiagofigueiro/nexus3-cli/commit/4a73b8a757b0239c2dc7e69ce336f8ccc8179ef2

**Comment by LindsayHill** [comment]
Looks like dropping Py2 was only supposed to be in the 2.x pre-release series? Or was that intentional dropping it in 1.0.2?

**Comment by MaciejKucia** [comment]
If python2 support was dropped then fine but it would be nice to have this reflected in pypi ;)

**Comment by thiagofigueiro** [comment]
@MaciejKucia Python 2 support was dropped in 1.0.1.  You're absolutely right: it should've been reflected in pypi and I should've announced the deprecation in 0.7.1 to warn users.  Mea culpa.

I'll push a new 1.x release to update the metadata on pypi. Sorry about this.

**Comment by thiagofigueiro** [comment]
Closing as I believe the questions have been answered. Feel free to comment if there are any more.
