### ISSUE TITLE
Cannot get API example working

### ISSUE THREAD

**Issue by adomenech73** [thiagofigueiro/nexus3-cli#63]
I cannot get the api example working, I don't know if this is related with 2.x upgrade but I'm using ```1.0.2```version.

```python
import nexuscli
nexus_config = nexuscli.nexus_config.NexusConfig(
        url=os.getenv('NEXUS_URL'),
        user=os.getenv('NEXUS_USER'),
        password=os.getenv('NEXUS_PWD'))
```
gets
```bash
Module 'nexuscli' has no 'nexus_config' member
```

**Comment by thiagofigueiro** [comment]
Hi, @adomenech73 - you're using an example from the 2.x version.  The 1.0.2 examples are in https://nexus3-cli.readthedocs.io/en/1.0.2/api/examples.html

```python
import nexuscli
nexus_client = nexuscli.nexus_client.NexusClient()
```

In any case, the example from 2.x is wrong: it would have been `import nexuscli.nexus_config`. I'll update that - thank you.
