### ISSUE TITLE
CLI documentation is missing

### ISSUE THREAD

**Issue by f18m** [thiagofigueiro/nexus3-cli#68]
I followed links to 
 https://nexus3-cli.readthedocs.io/en/latest/cli.html
but there is no real documentation for the CLI there, just for the API....

**Comment by thiagofigueiro** [comment]
Indeed.  I never got around to writing this doco.

The output of `nexus3-cli` should be somewhat self-explanatory.  I do want to do the docs one day, so I'll leave this issue open.  Thanks for reporting it.

**Comment by thiagofigueiro** [comment]
Fixed in 3.0.0
