### ISSUE TITLE
support for APT repositories

### ISSUE THREAD

**Issue by verhyppo** [thiagofigueiro/nexus3-cli#93]
It would be nice to have integration with all kind of repositories in order to facilitate the integration with nexus, removing unuseful scripts to setup and delete repositories. 

Here the issue for APT support.

**Comment by thiagofigueiro** [comment]
Thank you. Are you going to send a PR for this or would you like me to do it?

**Comment by verhyppo** [comment]
I had already implemented it in a fork of the projects just to support the api part, if it's ok for you I can open the PR as it's ready. I started yesterday the integration with the cli.

It would be great during the refactor of the cli you mentioned in your issue, to find a way to support other type of repositories provided via karaf packages, such as https://github.com/sonatype-nexus-community/nexus-repository-helm, as a future improvement, of course.

**Comment by verhyppo** [comment]
@thiagofigueiro I have a question about a mandatory fields for the apt repositories that breaks both `create hosted repository` and `create proxy repository` tests.

should I put the field as  optional with a default, even if they are mandatory?

**Comment by verhyppo** [comment]
At the moment I managed it with as optional

**Comment by thiagofigueiro** [comment]
I wrote this CLI to make it easier to manage Nexus, so having sensible defaults that allow you to get on with the job fit with the idea.

Optional with a default sounds good.

I'll go fix the CLI and then have a look at merging this so I can cut a release today.
